-- CreateTable
CREATE TABLE "Job" (
    "id" SERIAL NOT NULL,
    "ext_id" TEXT NOT NULL,
    "company_id" INTEGER NOT NULL,
    "company_name" TEXT NOT NULL,
    "company_logo" TEXT,
    "company_website_url" TEXT,
    "company_linkedin_url" TEXT,
    "company_twitter_handle" TEXT,
    "company_github_url" TEXT,
    "job_title" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "type_id" INTEGER NOT NULL,
    "type_name" TEXT NOT NULL,
    "city_geonameid" INTEGER,
    "city_asciiname" TEXT,
    "city_name" TEXT,
    "city_country_code" TEXT,
    "city_country_name" TEXT,
    "city_country_region_id" INTEGER,
    "city_country_region_name" TEXT,
    "city_timezone" TEXT,
    "city_latitude" TEXT,
    "city_longitude" TEXT,
    "country_code" TEXT,
    "country_name" TEXT,
    "country_region_id" INTEGER,
    "country_region_name" TEXT,
    "region_id" INTEGER,
    "region_name" TEXT,
    "has_remote" BOOLEAN,
    "published" TIMESTAMP(3) NOT NULL,
    "description" TEXT NOT NULL,
    "experience_level" TEXT,
    "application_url" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "clearance_required" BOOLEAN NOT NULL,
    "salary_min" DOUBLE PRECISION,
    "salary_max" DOUBLE PRECISION,
    "salary_currency" TEXT,

    CONSTRAINT "Job_pkey" PRIMARY KEY ("id")
);
